# General Course Overview {-}

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-kusv{background-color:#fffe65;border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-1o19{background-color:#67fd9a;text-align:left;vertical-align:top}
.tg .tg-glna{background-color:#fffe65;text-align:left;vertical-align:top}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-fymr{border-color:inherit;font-weight:bold;text-align:left;vertical-align:top}
.tg .tg-y6fn{background-color:#c0c0c0;text-align:left;vertical-align:top}
.tg .tg-4aw5{background-color:#96fffb;text-align:left;vertical-align:top}
.tg .tg-0lax{text-align:left;vertical-align:top}
.tg .tg-8m24{background-color:#000000;text-align:left;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-0pky" colspan="2">General Course Overview</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-fymr">Week Begining</td>
    <td class="tg-fymr">Focus</td>
  </tr>
  <tr>
    <td class="tg-kusv">5 Feb 24</td>
    <td class="tg-kusv" rowspan="4">Input from staff</td>
  </tr>
  <tr>
    <td class="tg-kusv">12 Feb 24</td>
  </tr>
  <tr>
    <td class="tg-kusv">19 Feb 24</td>
  </tr>
  <tr>
    <td class="tg-glna">26 Feb 24</td>
  </tr>
  <tr>
    <td class="tg-1o19">4 Mar 24</td>
    <td class="tg-1o19" rowspan="4">Output from students</td>
  </tr>
  <tr>
    <td class="tg-1o19">11 mar 24</td>
  </tr>
  <tr>
    <td class="tg-1o19">18 Mar 24</td>
  </tr>
  <tr>
    <td class="tg-1o19">25 Mar 24</td>
  </tr>
  <tr>
    <td class="tg-y6fn">1 Apr 24</td>
    <td class="tg-y6fn" rowspan="2">Easter break</td>
  </tr>
  <tr>
    <td class="tg-y6fn">8 Apr 24</td>
  </tr>
  <tr>
    <td class="tg-4aw5">15 Apr 24</td>
    <td class="tg-4aw5">Mentoring</td>
  </tr>
  <tr>
    <td class="tg-4aw5">22 Apr 24</td>
    <td class="tg-4aw5">Hand in this week</td>
  </tr>
  <tr>
    <td class="tg-0lax">26 April 24</td>
    <td class="tg-8m24"></td>
  </tr>
</tbody>
</table>
