---
always_allow_html: yes
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---
# Week by week detail {-}

<!-- This is a spoiler in gitbook, html and epub formats, and normal text otherwise. -->

Lectures,workshops and mentoring sessions will take place at the following times in weeks 19-26,29,30.

- **Thursday** 12:15-13:05 in 8W2.30 †

- **Friday** 12:15-14:05 in 1W2.104

† please note that in some of the Thursday sessions, the cohort will split into three different locations, each group with their own mentor. Details of this will be listed in the week summary below.

 <details>
<summary> Week 1 WB 6/2/23, click to reveal. </summary> 

::: {.information data-latex=""}
**Thursday 9/2/2023, 12:15-13:05 in 8W2.30**

Welcome.

What is Maths Communication?

Course information.
:::

$~$

::: {.information data-latex=""}
**Friday 10/2/2023, 12:15-14:05 in 1W2.104 **

Exploring the existing maths communication out there.

Setting up the 'Compare and Contrast' formative assessment.
:::

</details>


<details>
<summary>Week 2, WB 13/2/23, click to reveal. </summary> 

::: {.information data-latex=""}
**Thursday 16/2/2023, 12:15-13:05 in 8W2.30**

'Compare and Contrast' formative assessment discussions.

:::

$~$

::: {.information data-latex=""}
**Friday 17/2/2023, 12:15-14:05 in 1W2.104 **

Masterclasses overview.

Explore what a Masterclass is, tips on how to plan one and time to start your initial discussions.

:::

</details>

<details>
<summary> Week 3 WB 20/2/23, click to reveal. </summary> 

::: {.information data-latex=""}
**Thursday 23/2/2023, 12:15-13:05 in 8W2.30**

Aims and Objectives.

What are they? Examples in practice and their benefit for evaluation.
:::

$~$

::: {.information data-latex=""}
**Friday 24/2/2023, 12:15-14:05 in 1W2.104 **

The greatest hits of maths communication.

We will showcase a selection of the most used examples in the world of maths comm as inspiration for content choice and delivery options for your own delivery.

:::

</details>

<details>
<summary> Week 4 WB 27/2/23, click to reveal. </summary> 

::: {.mentoring data-latex=""}
**Thursday 2/3/2023, 12:15-13:05 in 8W2.30**

MENTORING

All groups will meet in person in 8W2.30

:::

$~$

::: {.information data-latex=""}
**Friday 3/3/2023, 12:15-14:05 in 1W2.104 **

Presentation skills and managing an audience

We will provide examples of a variety of presenter/audience interactions and highlight successful, and potential likely areas of breakdown, in this interaction.


:::

</details>

<details>
<summary> Week 5 WB 6/3/23, click to reveal. </summary> 

::: {.information data-latex=""}
**Thursday 8/3/2023, 12:15-14:05 in 1W2.104 **

*Masterclass pitches*:

Groups will pitch their initial ideas for their masterclass to the rest of the group. Groups should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.


Schedule:


12.20 Bath 18/3 Group

12:40 Holyport 18/3 Group


:::

$~$

::: {.information data-latex=""}
**Friday 10/3/2023, 12:15-14:05 in 1W2.104 **

*Continuation of Masterclass pitches*:

Groups will pitch their initial ideas for their masterclass to the rest of the group. Groups should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.


Schedule:


12:20 Oxford 18/3 group

12:40 Bath 25/3 group

13:20 Exeter 25/3 group


:::



