---
output:
  html_document: default
  pdf_document: default
---
# Other important dates and infomation{-}
<!-- This is a spoiler in gitbook, html and epub formats, and normal text otherwise. -->


<details>
<summary>Masterclass delivery dates. </summary> 
You will need to attend 1 of the following:

**18.3.23**


- Oxford Brookes University (10:00-12:30)


- Holyport (9.30-12.00)


- Bath University (10:00-12:30)


**25.3.23**


- Exeter Maths School (9:30-12:00)

- Bath University (10:00-12.30)

NB you will be allocated a date based on your response to the google form completed in December.

</details>



<details>
<summary>Coursework cover sheet. </summary> 
**Set:** *When issued: 9.2.23 12:15*.

**Due:** *Deadline: 28.4.23 11:59pm*.

**Estimated time required:** The coursework should take no more than *20 hours* to complete.

**Submission:** *Submit to the moodle page as a PDF; Your candidate name and number be included*

**Conditions:** *The report is an individual submission*

**Value:** *This written assignment carries 50\% of the total marks for the course.This assignment will be marked out of 50 where 25 marks are available for each section detailed on the assessment criteria.*

**Length:** There is a word count of 2500 words, 1250 words for your evaluation of Mathematical Interaction 1 and 1250 word for your evaluation of Mathemametical Interaction 2.

**Support and advice:** *You can ask you mentor for advice up until the deadline day in the designated mentoring sessions.*

**Feedback:** You will receive your marks for the unit at the same time as your other modules. 

**Late submission of coursework:** If there are valid circumstances preventing you from meeting the deadline, your Director of Studies may grant you an extension to the specified submission date, if it is requested before the deadline. Forms to request an extension are available on SAMIS.

* If you submit a piece of work after the submission date, and no extension has been granted, the maximum mark possible will be the pass mark.
* If you submit work more than five working days after the submission date, you will normally receive a mark of 0 (zero), unless you have been granted an extension.

**Academic integrity statement:** Academic misconduct is defined by the University as “the use of unfair means in any examination or assessment procedure”. This includes (but is not limited to) cheating, collusion, plagiarism, fabrication, or falsification. The University’s Quality Assurance Code of Practice, [QA53 Examination and Assessment Offences](https://www.bath.ac.uk/publications/qa53-examination-and-assessment-offences/), sets out the consequences of committing an offence and the penalties that might be applied.

**Contact details:**

*Tamsin Smith*<br>\newline
Room: *6W1.28* <br>\newline
E-mail: *t.l.smith@bath.ac.uk*

</details>