---
output:
  html_document: default
  pdf_document: default
---
# Masterclasses{-}
<!-- This is a spoiler in gitbook, html and epub formats, and normal text otherwise. -->

The Communicating Maths cohort will deliver 6 masterclasses over two weekends. Details are listed below.


Please find your group below to find details of your delivery group and the series you will attend.

<details>
<summary>Bath 16.3.24. </summary> 

::: {.information data-latex=""}
**Date:** *16.3.24*.

**Time:** *10:00-12:30*.

**Location:** *Bath University Campus*.

**Audience:** *Year 9, approx 100 participants*.

**University Mentor:** *Tam*.

**Masterclass Contact** *Chris Budd mascjb@bath.ac.uk*.

**Group Members:** *Jessica Smith, Freya Ong, Jamie Goas, Jon Stevens, Manasi Gaur and Mencia Berganza Zaragoza.*

**Initial pitch:** This group will pitch their initial ideas for their masterclass to the rest of the group at 12:20 on 7/3/24. You should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.

**Feedback:** After you have delivered your Masterclass you will receive verbal feedback, to support your written evaluation. This will be given by your mentor, who observed. Feedback slots will be approx 20 minutes long on 28/3/24. You will be expected to ask your mentor reflective questions to support your evaluation.

:::
</details>

<details>
<summary>Blandford School (Dorset) 16.3.24. </summary> 


::: {.information data-latex=""}
**Date:** *16.3.24*.

**Time:** *?*.

**Location:** *Blandford School*.

**Audience:** *?*.

**University Mentor:** *Ben*.

**Masterclass Contact** *Beth Hunt bhunt@blandfordschool.org.uk*.

**Group Members:** *Addie Baker, Julija Kazlauskaite,Oscar Harte, Ameen Hassan, Olivia Clarkson (Driver).*

**Initial pitch:** This group will pitch their initial ideas for their masterclass to the rest of the group at 12:40 on 7/3/24. You should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.

**Feedback:** After you have delivered your Masterclass you will receive verbal feedback, to support your written evaluation. This will be given by your mentor, who observed. Feedback slots will be approx 20 minutes long on 28/3/24. You will be expected to ask your mentor reflective questions to support your evaluation.

:::
</details>

<details>
<summary>Holyport College 16.3.24. </summary> 

::: {.information data-latex=""}
**Date:** *16.3.24*.

**Time:** *9:30-12:00*.

**Location:** *Holyport College*.

**Audience:** *Year 9, approx 45 participants*.

**University Mentor:** *Waleed (your assessor will be Sam Durbin from the Ri sdurbin@ri.ac.uk)*.

**Masterclass Contact** *Daniel Hubbard d.hubbard@holyportcollege.org.uk and Aisha Saeed a.saeed@holyportcollege.org.uk*.

**Group Members:** *Ethan Attwood, Hadiyah Qureshi, Matthew Hall, Ellie Smyth (Driver), Will Carpenter (Driver).*

**Initial pitch:** This group will pitch their initial ideas for their masterclass to the rest of the group at 12:20 on 8/3/24. You should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.

**Feedback:** After you have delivered your Masterclass you will receive verbal feedback, to support your written evaluation. This will be given by your assessor (Samantha Durbin), who observed. Feedback slots will be approx 20 minutes long on or around the 28/3/24, time mutually agreed. You will be expected to ask your assessor reflective questions to support your evaluation.
:::
</details>

<details>
<summary>Swansea 16.3.24. </summary> 


::: {.information data-latex=""}
**Date:** *16.3.24*.

**Time:** *?*.

**Location:** *Swansea University Campus*.

**Audience:** *?*.

**University Mentor:** *Waleed*.

**Masterclass Contact** *Sofya Lyakhova s.lyakhova@swansea.ac.uk*.

**Group Members:** *Ajay Bater, Jenna Benbow, Nina Peric, Dandan Zhang, Dylan Flanagan (Driver).*

**Initial pitch:** This group will pitch their initial ideas for their masterclass to the rest of the group at 12:40 on 8/3/24. You should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.

**Feedback:** After you have delivered your Masterclass you will receive verbal feedback, to support your written evaluation. This will be given by your mentor, who observed. Feedback slots will be approx 20 minutes long on 28/3/24. You will be expected to ask your mentor reflective questions to support your evaluation.

:::
</details>

<details>
<summary>Bath 23.3.24. </summary> 


::: {.information data-latex=""}
**Date:** *23.3.24*.

**Time:** *10:00-12:30*.

**Location:** *Bath University Campus*.

**Audience:** *Year 9, approx 100 participants*.

**University Mentor:** *Ben*.

**Masterclass Contact** *Chris Budd mascjb@bath.ac.uk*.

**Group Members:** *Alfie Robinson, Emily Howard, Kieran Breathnach, Liam Jones, Marta Breton de la Cierva, Leila Ingram-Smith*

**Initial pitch:** This group will pitch their initial ideas for their masterclass to the rest of the group at 13:15 on 8/3/24. You should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.

**Feedback:** After you have delivered your Masterclass you will receive verbal feedback, to support your written evaluation. This will be given by your mentor, who observed. Feedback slots will be approx 20 minutes long on 28/3/24. You will be expected to ask your mentor reflective questions to support your evaluation.
:::
</details>

<details>
<summary>Exeter 23.3.24. </summary> 

::: {.information data-latex=""}
**Date:** *23.3.24*.

**Time:** *9:30-12:00*.

**Location:** *Exeter School of Maths*.

**Audience:** *Year 9, approx 30 participants*.

**University Mentor:** *Tam*.

**Masterclass Contact** *Jo Events@exetermathematicsschool.ac.uk*

**Group Members:** *Lucia Garcia, Amy Best, Henry Reeves, Joe Addisson, Matt Landau (Driver)*

**Initial pitch:** This group will pitch their initial ideas for their masterclass to the rest of the group at 13:35 on 8/3/24. You should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.

**Feedback:** After you have delivered your Masterclass you will receive verbal feedback, to support your written evaluation. This will be given by your mentor, who observed. Feedback slots will be approx 20 minutes long on 28/3/24. You will be expected to ask your mentor reflective questions to support your evaluation.
:::
</details>


