--- 
title: "Communicating Maths Information"
author: "Tamsin Smith"
date: "`2024`"
output:
  bookdown::gitbook:
    css: style.css
    mathjax:
      loader:
        load: '[tex]/cancel'
      tex:
        packages:
          '[+]': cancel
site: bookdown::bookdown_site
documentclass: book
description: Important information for communicating maths students 2023.
always_allow_html: yes
---

```{r, setup, include=FALSE}
# This allows knitr to automagically take a screen shot of any html used
# in the documents and then use that image in the pdfs it generates
# delay = 2 - this gives time for the webpage to load before taking the screen shot.
# cliprect = 'viewport' - 
# vheight = 800 - this is set to the same as the height of the embedded NUMBAS questions
library(webshot2)
knitr::opts_chunk$set(
  screenshot.opts = list(delay = 2, cliprect = 'viewport', vheight = 800)
)
```

# Welcome {-}

This document contains an overview of important dates and details for communicating maths students 2024. This document will update as the semester progresses.


<!--chapter:end:index.Rmd-->

# General Course Overview {-}

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-kusv{background-color:#fffe65;border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-1o19{background-color:#67fd9a;text-align:left;vertical-align:top}
.tg .tg-glna{background-color:#fffe65;text-align:left;vertical-align:top}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-fymr{border-color:inherit;font-weight:bold;text-align:left;vertical-align:top}
.tg .tg-y6fn{background-color:#c0c0c0;text-align:left;vertical-align:top}
.tg .tg-4aw5{background-color:#96fffb;text-align:left;vertical-align:top}
.tg .tg-0lax{text-align:left;vertical-align:top}
.tg .tg-8m24{background-color:#000000;text-align:left;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-0pky" colspan="2">General Course Overview</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-fymr">Week Begining</td>
    <td class="tg-fymr">Focus</td>
  </tr>
  <tr>
    <td class="tg-kusv">5 Feb 24</td>
    <td class="tg-kusv" rowspan="4">Input from staff</td>
  </tr>
  <tr>
    <td class="tg-kusv">12 Feb 24</td>
  </tr>
  <tr>
    <td class="tg-kusv">19 Feb 24</td>
  </tr>
  <tr>
    <td class="tg-glna">26 Feb 24</td>
  </tr>
  <tr>
    <td class="tg-1o19">4 Mar 24</td>
    <td class="tg-1o19" rowspan="4">Output from students</td>
  </tr>
  <tr>
    <td class="tg-1o19">11 mar 24</td>
  </tr>
  <tr>
    <td class="tg-1o19">18 Mar 24</td>
  </tr>
  <tr>
    <td class="tg-1o19">25 Mar 24</td>
  </tr>
  <tr>
    <td class="tg-y6fn">1 Apr 24</td>
    <td class="tg-y6fn" rowspan="2">Easter break</td>
  </tr>
  <tr>
    <td class="tg-y6fn">8 Apr 24</td>
  </tr>
  <tr>
    <td class="tg-4aw5">15 Apr 24</td>
    <td class="tg-4aw5">Mentoring</td>
  </tr>
  <tr>
    <td class="tg-4aw5">22 Apr 24</td>
    <td class="tg-4aw5">Hand in this week</td>
  </tr>
  <tr>
    <td class="tg-0lax">26 April 24</td>
    <td class="tg-8m24"></td>
  </tr>
</tbody>
</table>

<!--chapter:end:01_General_overview.Rmd-->

---
always_allow_html: yes
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---
# Week by week detail {-}

<!-- This is a spoiler in gitbook, html and epub formats, and normal text otherwise. -->

Lectures,workshops and mentoring sessions will take place at the following times in weeks 19-22,

- **Tuesday** 10:15-11:05 in 1W2.01 
 
- **Thursday** 12:15-13:05 in 8W2.30 

- **Friday** 12:15-14:05 in 1W2.104

- **Friday** 17:15-18:05 in 8W2.10

Lectures,workshops and mentoring sessions will take place at the following times in weeks 23-26,29-32

- **Thursday** 12:15-13:05 in 8W2.30 

- **Friday** 12:15-14:05 in 1W2.104



Please note that in some of the sessions listed above, the cohort will split into three different locations, each group with their own mentor or group. Details of this will be listed in the week summary below.



<!---
 <details>
<summary> Week 1 WB 6/2/23, click to reveal. </summary> 

::: {.information data-latex=""}
**Thursday 9/2/2023, 12:15-13:05 in 8W2.30**

Welcome.

What is Maths Communication?

Course information.
:::

$~$

::: {.information data-latex=""}
**Friday 10/2/2023, 12:15-14:05 in 1W2.104 **

Exploring the existing maths communication out there.

Setting up the 'Compare and Contrast' formative assessment.
:::

</details>


<details>
<summary>Week 2, WB 13/2/23, click to reveal. </summary> 

::: {.information data-latex=""}
**Thursday 16/2/2023, 12:15-13:05 in 8W2.30**

'Compare and Contrast' formative assessment discussions.

:::

$~$

::: {.information data-latex=""}
**Friday 17/2/2023, 12:15-14:05 in 1W2.104 **

Masterclasses overview.

Explore what a Masterclass is, tips on how to plan one and time to start your initial discussions.

:::

</details>

<details>
<summary> Week 3 WB 20/2/23, click to reveal. </summary> 

::: {.information data-latex=""}
**Thursday 23/2/2023, 12:15-13:05 in 8W2.30**

Aims and Objectives.

What are they? Examples in practice and their benefit for evaluation.
:::

$~$

::: {.information data-latex=""}
**Friday 24/2/2023, 12:15-14:05 in 1W2.104 **

The greatest hits of maths communication.

We will showcase a selection of the most used examples in the world of maths comm as inspiration for content choice and delivery options for your own delivery.

:::

</details>

<details>
<summary> Week 4 WB 27/2/23, click to reveal. </summary> 

::: {.mentoring data-latex=""}
**Thursday 2/3/2023, 12:15-13:05 in 8W2.30**

MENTORING

All groups will meet in person in 8W2.30

:::

$~$

::: {.information data-latex=""}
**Friday 3/3/2023, 12:15-14:05 in 1W2.104 **

Presentation skills and managing an audience

We will provide examples of a variety of presenter/audience interactions and highlight successful, and potential likely areas of breakdown, in this interaction.


:::

</details>

<details>
<summary> Week 5 WB 6/3/23, click to reveal. </summary> 

::: {.information data-latex=""}
**Thursday 8/3/2023, 12:15-13:05 in 1W2.104 **

*Masterclass pitches*:

Groups will pitch their initial ideas for their masterclass to the rest of the group. Groups should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.


Schedule:


12.20 Bath 18/3 Group

12:40 Holyport 18/3 Group


:::

$~$

::: {.information data-latex=""}
**Friday 10/3/2023, 12:15-14:05 in 1W2.104 **

*Continuation of Masterclass pitches*:

Groups will pitch their initial ideas for their masterclass to the rest of the group. Groups should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.


Schedule:


12:20 Oxford 18/3 group

12:40 Bath 25/3 group

13:20 Exeter 25/3 group


:::

</details>

<details>
<summary> Week 6 WB 13/3/23, click to reveal. </summary> 

::: {.mentoring data-latex=""}
**Thursday 16/3/2023, 12:15-13:05 **
Mentoring:

Tamsin online mentoring:
[Teams link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MTE5ZGJiZTQtYjcxZS00ZWQ5LWIzNmQtMjI5MDA1NjBjNmY1%40thread.v2/0?context=%7b%22Tid%22%3a%22377e3d22-4ea1-422d-b0ad-8fcc89406b9e%22%2c%22Oid%22%3a%22ecc800ca-2608-4db3-b8ee-813070b681cf%22%7d 
)
8W2.22 is booked and available if you wish to join together.

Ben in 8W2.30


Waleed in 8W2.30


:::

$~$

::: {.information data-latex=""}
**Friday 17/3/2023, 12:15-13:05 in 1W2.104 **

*MI2 advice sessions*:

The group will split into 3 sections (Schools Placement/Article/Video) to discuss good practise.

**Friday 17/3/2023, 13:05-14:05 in 1W2.104 **

*Assessment support*:

The session will address how you will be assessed and things to think about to improve your grade.This will have specific reference to your written report.



:::

</details>

<details>
<summary> Week 7 WB 20/3/23, click to reveal. </summary> 

::: {.information data-latex=""}
**Thursday 23/3/2023, 12:15-13:05 **

Mathematical Interaction 2 pitches.

The following people will need to present a 3-4 min pitch on their School Placement. They will repeat this pitch multiple times to their peers and staff to gain feedback and ideas.

Mira Balaji,
Abigail Bennett,
Anna Quinn,
 Zoe Fairfax, 
Chloe Howcroft,  
Ashley Higgs, 
Joy Boh,
Ewan Partington,
Rhea Shah.

:::

$~$

::: {.information data-latex=""}
**Friday 24/3/2023, 12:15-13:05 in 1W2.104 **

Mathematical Interaction 2 pitches.

The following people will need to present a 3-4 min pitch on their Article or Video. They will repeat this pitch multiple times to their peers and staff to gain feedback and ideas.

Lucia Lopez,
Molly Maguire King,
Alankrit Mata,
Andrew McGrath,
Samantha Perryman,
Tali Shear,
Haranja Sivaneswaran,
Olivia Wiseman,
Jodie Young.



:::



$~$

:::: {.mentoring data-latex=""}
**Friday 24/3/2023, 13:05-14:05 in 1W2.104 **

Mentoring on Mathematical Interaction 2

:::

</details>

<details>
<summary> Week 8 WB 27/3/23, click to reveal. </summary> 

::: {.Feedback data-latex=""}
**Thursday 30/3/2023, 12:15-13:05 **

Formal feedback:

Each Master class group will receive 20 minutes of structured feedback to support the writing of your report. 


Each school placement individual/pair will receive 10 minutes of feedback. 

The schedule of feedback times and locations are detailed below.

<u>**Feedback in 8W 2.15**</u>



11:55 Abi/Tam School Placement

12:05 Chloe/Tam School Placement

12:15 Bath 18th Masterclass group/Tam

12:35 Ashley/Joy/Tam School Placement

12:45 Ewan/Tam School Placement

12:55 Anna School Placement/Tam




<u>**Feedback in 8W 2.30**</u>

12:15 Oxford 18th Masterclass group/Ben

12:35 Bath 25th Masterclass group/Ben



<u>**Feedback in 1WN3.11**</u>

12:05 Zoe School Placement/Waleed

12:15 Holyport 18th Masterclass group/Waleed

12:35 Exeter 25 Masterclass group/Waleed

12:55 Mira/Rhea/Waleed School Placement





:::

$~$

::: {.information data-latex=""}
**Friday 31/3/2023, 12:15-13:05 in 1W2.104 **

Mathematical Interaction 2 pitches.

The following people will need to present a 3-4 min pitch on their Article or Video. They will repeat this pitch multiple times to their peers and staff to gain feedback and ideas.

Kamila Bugno,
Sam Cheung,
Tosia Ciszek,
Mirren  Derby,
Tom Eves,
Timi Folaranmi,
Lana Gregory,
Ella Hidveghy,
Rebecca Knight.




:::



$~$

:::: {.mentoring data-latex=""}
**Friday 31/3/2023, 13:05-14:05 in 1W2.104 **

Mentoring on Mathematical Interaction 2

:::
</details>
<details>
<summary> Week 9 WB 17/4/23, click to reveal. </summary>

:::: {.mentoring data-latex=""}
**Thursday 20/4/2023, 12:05-13:05 in 8W2.30 **

Mentoring (report writing)

Tam and Ben in 8W2.30

Waleed will be online click to join teams meeting [here](https://eur01.safelinks.protection.outlook.com/ap/t-59584e83/?url=https%3A%2F%2Fteams.microsoft.com%2Fl%2Fmeetup-join%2F19%253ameeting_ZDA3ODRjZDctYjI3OS00YmVlLWI2ODctZGYyYzJlZWE0OWE3%2540thread.v2%2F0%3Fcontext%3D%257b%2522Tid%2522%253a%2522377e3d22-4ea1-422d-b0ad-8fcc89406b9e%2522%252c%2522Oid%2522%253a%252271257a1e-ed1c-4d32-867a-83234b865cac%2522%257d&data=05%7C01%7Ctls35%40bath.ac.uk%7Cb6d5434c25874774ec1508db404062b8%7C377e3d224ea1422db0ad8fcc89406b9e%7C0%7C0%7C638174417487020259%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mUuUeUcIk1VC4wz99jZ4CniIwaXnnXl4lP9lclK4Oqk%3D&reserved=0)

Meeting ID: 383 018 763 306 
Passcode: Nv7fxD 


:::

::: {.information data-latex=""}
**Friday 21/4/2023, 12:05-14:05 in 1W2.104 **

Report writing discussion and activity.

We will be using a guest speaker (Dr Katie Steckles) as an exemplar to explore possible report content and techniques.


:::

</details>

<details>
<summary> Week 10 WB 24/4/23, click to reveal. </summary>

:::: {.mentoring data-latex=""}
**Thursday 27/4/2023, 12:05-13:05 in 8W2.30 **

Mentoring (report writing)


Waleed and Ben in 8W2.30

Tam will be online click to join teams meeting [here](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MjNkYzJlZDctYzhmNC00NGQ4LWJkZDUtM2VmZWI3NGE0MzY3%40thread.v2/0?context=%7b%22Tid%22%3a%22377e3d22-4ea1-422d-b0ad-8fcc89406b9e%22%2c%22Oid%22%3a%22ecc800ca-2608-4db3-b8ee-813070b681cf%22%7d)

Meeting ID: 372 883 434 284 
Passcode: 5oVyMt 


:::

::: {.handin data-latex=""}
**Friday 28/4/2023, 12:05-14:05 in 1W2.104 **

HAND IN DAY!

Final session - bring  trick.




:::

</details>

<!--chapter:end:02_Week_by_week.Rmd-->

---
output:
  html_document: default
  pdf_document: default
---
# Assessment information{-}

<details>
<summary>Assessment credit breakdown. </summary>

The Assessment of the course will be based around two Mathematical Interactions (MI's). 

A **Mathematical Interaction** (MI) is defined as the communication of mathematics to an audience.

Typically:

* MI1 is an Ri Masterclass, planned and delivered as a group.

* MI2 is an option from video, article or school placement, planned and delivered as an individual or pair.

Each of the two MI's will be summatively assessed in two parts:

A) The live And recorded delivery; 25% of the overall course mark

B)  The written evaluation; 25% of the overall course mark

Overall this is how the marks for the course will be allocated:

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-f7v4{background-color:#c0c0c0;border-color:#000000;text-align:left;vertical-align:top}
.tg .tg-mfjn{background-color:#333333;border-color:#000000;color:#ffffff;text-align:left;vertical-align:top}
.tg .tg-iks7{background-color:#ffffff;border-color:#000000;text-align:left;vertical-align:top}
</style>
<table class="tg" style="undefined;table-layout: fixed; width: 407px">
<colgroup>
<col style="width: 175.333333px">
<col style="width: 115.333333px">
<col style="width: 116.666666px">
</colgroup>
<thead>
  <tr>
    <th class="tg-mfjn"></th>
    <th class="tg-f7v4">Delivery</th>
    <th class="tg-f7v4">Evaluation report</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-f7v4">Mathematical Interaction 1</td>
    <td class="tg-iks7">25%</td>
    <td class="tg-iks7">25%</td>
  </tr>
  <tr>
    <td class="tg-f7v4">Mathematical Interaction 2</td>
    <td class="tg-iks7">25%</td>
    <td class="tg-iks7">25%</td>
  </tr>
</tbody>
</table>

The assessment criteria for each part can be found in Assessment submission topic file on moodle or in the list below titled Assessment Criteria.
</details>

<details>
<summary>Coursework cover sheet. </summary> 
**Set:** When issued: 6.2.24 10:15.

**Due:** Deadline: 26.4.24 11:59pm.

**Estimated time required:** The coursework should take no more than *30 hours* to complete. This is an upper bound and most students will complete the written report in less time. 

**Submission:** Submit to the moodle page as a PDF; Your candidate name and number be included.

**Conditions:** The report is an individual submission.

**Value:** This written assignment carries 50\% of the total marks for the course.This assignment will be marked out of 50 where 25 marks are available for each section detailed on the assessment criteria.

**Length:** There is a word count of 2500 words, 1250 words for your evaluation of Mathematical Interaction 1 and 1250 word for your evaluation of Mathemametical Interaction 2.

**Support and advice:** You can ask you mentor for advice up until the deadline day in the designated mentoring sessions.

**Feedback:** You will receive your marks for the unit at the same time as your other modules. 

**Late submission of coursework:** If there are valid circumstances preventing you from meeting the deadline, your Director of Studies may grant you an extension to the specified submission date, if it is requested before the deadline. Forms to request an extension are available on SAMIS.

* If you submit a piece of work after the submission date, and no extension has been granted, the maximum mark possible will be the pass mark.
* If you submit work more than five working days after the submission date, you will normally receive a mark of 0 (zero), unless you have been granted an extension.

**Academic integrity statement:** Academic misconduct is defined by the University as “the use of unfair means in any examination or assessment procedure”. This includes (but is not limited to) cheating, collusion, plagiarism, fabrication, or falsification. The University’s Quality Assurance Code of Practice, [QA53 Examination and Assessment Offences](https://www.bath.ac.uk/publications/qa53-examination-and-assessment-offences/), sets out the consequences of committing an offence and the penalties that might be applied.

**Contact details:**

*Tamsin Smith*<br>\newline
Room: *2S1.04* <br>\newline
E-mail: *t.l.smith@bath.ac.uk*

</details>

<details>
<summary>Group Contributions. </summary>

*Group Contribution Rating (GCR)*

For the elements of the course where you will present material as a group, group members must agree on one another’s relative contribution to their coursework. We will assume that groups agree to an even allocation of marks across the group unless a Group Contribution Form (GCF) is submitted to the unit convener.

*The Group Contribution Form (GCF)*

The GCF is available on the Moodle page and records how well individual members have contributed to the coursework throughout the coursework period. The final GCF is a one-page document with every group member’s name, signature and agreed assessment of their percentage contribution to the coursework over the whole coursework period. In the case that recorded percentage contributions are exceptionally high or low, the GCF document should include a brief paragraph of explanation. (An example can be found Assessment submission topic file). The signed GCF must be submitted to the unit convener after the live delivery. If no agreement can be reached on the contributions of individual members, the group can hand in more than one GCF, but members will be required to produce evidence in a hearing with the unit convener to support their argument. In such an eventuality, the Director of Teaching may also be involved. The GCF will directly inform the allocation of marks to each individual group member.



</details>

<details>
<summary>Assessment Criteria. </summary>

**Live and recorded delivery descriptors.**


*Grid A* will be used to mark the content of each Mathematical Interaction (which could be one of the below items):

* COMPULSORY - Masterclasses: Live delivery - in groups
$~$
* OPTION - Written article
suitable for Chalkdust, published on Medium - individual work
* OPTION - Video
published on YouTube, e.g. similar in style to Numberphile, StandupMaths, 3Blue1Brown. Maximum 2 in group.
* OPTION - School placement
to be arranged in local school (limited availability)


**Written Evaluation descriptors**

*Grid B* will be used to mark the written evaluation of each Mathematical Interaction.


See below for Grid A and B, please note that a one page pdf document of these tables is available on moodle.


*Grid A*

|     Mark    |     Mathematical Content     (e.g. equations, derivations, proofs   and correctness/appropriateness of these)                                                  |     Communication with media and   demonstration     (e.g. slides, physical props, board   use, graphics/animation, handouts etc)    |     Style and Delivery    (e.g technique, audience handling, confidence, clarity, surprise, humour,   variety, tone)                                             |     Structure and pacing     (e.g sections, pace, flow,   narrative, coherence)                                                                                       |     Appropriateness for Audience                                                                                                                                                                                                    |
|-------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|     5       |     Detailed   and consistent understanding of the content.     Fully   correct and appropriate mathematics.     Awareness   of wider context demonstrated.    |     Fully   developed use of media.     Successful,   creative, or original demonstrations.                                          |     Well   developed general style and delivery.     Delivery is   clear, and engages well with the audience, using a range of successful   techniques.          |     Fully   appropriate structure and pace.     Well chosen   quantity and ordering of material gives a complete narrative.                                           |     Fully   developed understanding of the intended audience and their prior knowledge.     Progression   of the material, from an appropriate entry level, is successfully managed and   enhances audience interest/experience.    |
|     4       |     Detailed   understanding of the content.     Mostly   correct and appropriate mathematics.                                                                 |     Mostly   developed use of media.     Mostly   successful, creative, or original demonstrations.                                  |     General   style and delivery is well developed in places.     Delivery   engages well with the audience, using some successful techniques.                   |     Appropriate   structure and pace.     Quantity   and order of material fits structure and aids narrative.                                                         |     Mostly   developed understanding of the intended audience and their prior knowledge.     Progression   of the material achieved, from an appropriate entry level.                                                               |
|     3       |     Some   misunderstanding of the content is apparent.     Some   mathematical inaccuracies or omissions.                                                     |     Some media   used inappropriately, otherwise resources and media are adequate.     Some   successful demonstrations.             |     Some good   style and delivery.     Occasional   problems with clarity or audience engagement.                                                               |     Some   evidence of structure and some sections well paced.     Some   problems with quantity or ordering of material which affect the narrative.                  |     Some   understanding of the intended audience and their prior knowledge.     Some   progression of material is successfully managed.     Some   material occasionally inappropriate for the audience.                           |
|     2       |     Significant   misunderstanding of the content is apparent.     Significant   mathematical inaccuracies or omissions.                                       |     Significant   problems with use of media, even if some are used well.     Significant   problems with demonstrations.            |     Significant   problems with style or delivery, with negative consequences for audience   engagement (observed or likely).                                    |     Minimal   structure apparent or significant problems with pacing.     Significant   problems with quantity or ordering of material which affect the narrative.    |     Minimal   understanding of the audience and their prior knowledge.     Significant   problems with level of material and progression.                                                                                           |
|     1       |     Very   limited understanding of content      Minimal   mathematical content.                                                                               |     Very   limited use of media.     Very   limited demonstrations.                                                                  |     Very   limited style and delivery throughout, resulting in continued audience   disengagement (observed or likely).                                          |     Very   limited or no structure     Very   limited pacing.     No   overarching narrative.                                                                         |     Very   limited  understanding of the audience.     Inappropriate   level and progression of material.                                                                                                                           |
|     0       |     No   mathematical content.                                                                                                                                 |     No use of   media or demonstrations.                                                                                             |     No   presentation or work submitted.                                                                                                                         |     No   presentation or work submitted.                                                                                                                              |     No indication   or awareness of the intended audience or their level.                                                                                                                                                           |                                                                                                                                               |

*Grid B*

| Mark | Aims, Objectives and Intentions                                                                                                                                                        | Collection and analysis of Feedback                                                                                                                                                 | Positive reflections                                                                                                                                                                                                  | Potential Improvements                                                                                                                                                                                                                    | Overall quality of written communication                                             |
|------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------|
| 5    | Fully appropriate aims and objectives that are clear, attainable, and appropriate. Fully developed discussion of intentions with reasons, and the specific actions to accomplish them. | Fully developed plan for collecting appropriate feedback from the audience. Detailed analysis of the quantity and quality of feedback received using meaningful summary techniques. | Fully developed discussion of what went well, and why.  Clear and detailed reflection on success of meeting the overall aims and objectives.  Characterised by mature reflective judgement on the impact of the work. | Fully developed  discussion of what did not work well, and how things could be improved. Clear reflection on failure of meeting the overall aims and objectives.  Characterised by mature reflective judgement on the impact of the work. | Ideas expressed clearly, concisely, and with excellent structure.                    |
| 4    | Appropriate aims and objectives that are mostly clear, attainable, and appropriate. Appropriate discussion of intentions.                                                              | Developed methods of feedback collection feedback from the audience. Analysis of the quantity or quality of feedback received using meaningful summary techniques.                  | Developed discussion of what went well, and why. Clear reflection on success of meeting the overall aims and objectives.                                                                                              | Developed discussion of what did not work well. Clear reflection on failures of meeting the overall aims and objectives.                                                                                                                  | Ideas are generally expressed well, and with appropriate structure.                  |
| 3    | Fairly clear aims and objectives some of which are clear, attainable, and appropriate. Partial discussion of intentions/reasons.                                                       | Some evidence of feedback collected, but of varying quality and usefulness. Some discussion/analysis, possibly presented inefficiently.                                             | Some awareness of what went well and only partial discussion of the reasons for this.                                                                                                                                 | Some awareness of what did not work well and only partial discussion of the reasons for this.                                                                                                                                             | Ideas are generally expressed fairly clearly, with reasonably appropriate structure. |
| 2    | Mostly unhelpful aims and objectives, which are not clear, obtainable or appropriate. Minimal discussion of intentions/reasons.                                                        | Minimal planning for feedback leading to little discussion or analysis.                                                                                                             | Minimal awareness of what went well. Obvious success points missed or not discussed.                                                                                                                                  | Minimal awareness of what did not work  well. Obvious failure points missed or not discussed                                                                                                                                              | Ideas are rarely expressed coherently. Structure is less appropriate.                |
| 1    | Aims or objectives are unhelpful or vague, and few or none are clear or obtainable. Very limited discussion of intentions/reasons.                                                     | Very limited  planning for feedback collection and little or no discussion or analysis.                                                                                             | Very limited awareness/reflection on any success.                                                                                                                                                                     | Very limited awareness/reflection on any failure.                                                                                                                                                                                         | Ideas are expressed incoherently.  Limited structure.                                |
| 0    | No aims or objectives set.                                                                                                                                                             | No attempt at feedback collection, discussion, or analysis.                                                                                                                         | No awareness of positive  aspects of work.                                                                                                                                                                            | No awareness of negative  aspects of work.                                                                                                                                                                                                | No written work submitted.                                                           |

<!---
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black !important;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-abx8{background-color:#c0c0c0;font-weight:bold;text-align:left;vertical-align:top}
.tg .tg-ycr8{background-color:#ffffff;text-align:left;vertical-align:top}
.tg .tg-f7v4{background-color:#c0c0c0;border-color:#000000;text-align:left;vertical-align:top}
.tg .tg-0lax{text-align:left;vertical-align:top}
.tg .tg-rv8b{background-color:#c0c0c0;border-color:#000000;color:#ffffff;font-weight:bold;text-align:left;vertical-align:top}
.tg .tg-cscf{background-color:#c0c0c0;border-color:#000000;font-weight:bold;text-align:left;vertical-align:top}
.tg .tg-iks7{background-color:#ffffff;border-color:#000000;text-align:left;vertical-align:top}
.tg .tg-y6fn{background-color:#c0c0c0;text-align:left;vertical-align:top}
</style>
<table class="tg" style="undefined;table-layout: fixed; width: 704px">
<colgroup>
<col style="width: 83.333333px">
<col style="width: 124.333333px">
<col style="width: 123.666666px">
<col style="width: 124.333333px">
<col style="width: 124.333333px">
<col style="width: 124.333333px">
</colgroup>
<thead>
  <tr>
    <th class="tg-0lax" colspan="6">GRID A</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-rv8b"><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000">Mark</span></td>
    <td class="tg-cscf"><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000">Mathematical Content</span><br><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000">(e.g. equations, derivations, proofs and correctness/appropriateness of these)</span></td>
    <td class="tg-cscf"><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000">Communication with media and demonstration</span><br><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000">(e.g. slides, physical props, board use, graphics/animation, handouts etc)</span></td>
    <td class="tg-abx8"><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000">Style and Delivery(e.g technique, audience handling, confidence, clarity, surprise, humour, variety, tone)</span></td>
    <td class="tg-abx8"><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000">Structure and pacing</span><br><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000">(e.g sections, pace, flow, narrative, coherence)</span></td>
    <td class="tg-abx8"><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000">Appropriateness for Audience</span></td>
  </tr>
  <tr>
    <td class="tg-f7v4"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">5</span></td>
    <td class="tg-iks7"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Detailed and consistent understanding of the content.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Fully correct and appropriate mathematics.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Awareness of wider context demonstrated.</span></td>
    <td class="tg-iks7"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Fully developed use of media.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Successful, creative, or original demonstrations.</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Well developed general style and delivery</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Delivery is clear, and engages well with the audience, using a range of successful techniques.</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Fully appropriate structure and pace.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Well chosen quantity and ordering of material gives a complete narrative.</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Fully developed understanding of the intended audience and their prior knowledge.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Progression of the material, from an appropriate entry level, is successfully managed and enhances audience interest/experience.</span></td>
  </tr>
  <tr>
    <td class="tg-f7v4"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">4</span></td>
    <td class="tg-iks7"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Detailed understanding of the content.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Mostly correct and appropriate mathematics.</span></td>
    <td class="tg-iks7"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Mostly developed use of media.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Mostly successful, creative, or original demonstrations.</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">General style and delivery is well developed in places</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Delivery engages well with the audience, using some successful techniques</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Appropriate structure and pace.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Quantity and order of material fits structure and aids narrative.</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Mostly developed understanding of the intended audience and their prior knowledge.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Progression of the material achieved, from an appropriate entry level.</span></td>
  </tr>
  <tr>
    <td class="tg-y6fn"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">3</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Some misunderstanding of the content is apparent.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Some mathematical inaccuracies or omissions.</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Some media used inappropriately, otherwise resources and media are adequate</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Some successful demonstrations.</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Some good style and delivery.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Occasional problems with clarity or audience engagement.</span><br></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Some evidence of structure and some sections well paced.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Some problems with quantity or ordering of material which affect the narrative.</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Some understanding of the intended audience and their prior knowledge.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Some progression of material is successfully managed.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Some material occasionally inappropriate for the audience </span></td>
  </tr>
  <tr>
    <td class="tg-y6fn"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">2</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Significant misunderstanding of the content is apparent.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Significant mathematical inaccuracies or omissions</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Significant problems with use of media, even if some are used well.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Significant problems with demonstrations</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Significant problems with style or delivery, with negative consequences for audience engagement (observed or likely)</span><br></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Minimal structure apparent or significant problems with pacing.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Significant problems with quantity or ordering of material which affect the narrative.</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Minimal understanding of the audience and their prior knowledge.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Significant problems with level of material and progression.</span></td>
  </tr>
  <tr>
    <td class="tg-y6fn"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">1</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Very limited understanding of content </span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Minimal mathematical content</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Very limited use of media.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Very limited demonstrations.</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Very limited style and delivery throughout, resulting in continued audience disengagement (observed or likely)</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Very limited or no structure</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Very limited pacing.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">No overarching narrative.</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Very limited  understanding of the audience.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">Inappropriate level and progression of material</span></td>
  </tr>
  <tr>
    <td class="tg-y6fn"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">0</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">No mathematical content</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">No use of media or demonstrations</span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">No presentation or work submitted </span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">No presentation or work submitted </span></td>
    <td class="tg-ycr8"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">No indication or awareness of the intended audience or their level.</span></td>
  </tr>
</tbody>
</table>
$~$
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-abx8{background-color:#c0c0c0;font-weight:bold;text-align:left;vertical-align:top}
.tg .tg-llyw{background-color:#c0c0c0;border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-f7v4{background-color:#c0c0c0;border-color:#000000;text-align:left;vertical-align:top}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-rv8b{background-color:#c0c0c0;border-color:#000000;color:#ffffff;font-weight:bold;text-align:left;vertical-align:top}
.tg .tg-cscf{background-color:#c0c0c0;border-color:#000000;font-weight:bold;text-align:left;vertical-align:top}
.tg .tg-6e8n{background-color:#c0c0c0;border-color:inherit;font-weight:bold;text-align:left;vertical-align:top}
.tg .tg-iks7{background-color:#ffffff;border-color:#000000;text-align:left;vertical-align:top}
.tg .tg-c6of{background-color:#ffffff;border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg" style="undefined;table-layout: fixed; width: 704px">
<colgroup>
<col style="width: 83.333333px">
<col style="width: 123.666666px">
<col style="width: 124.333333px">
<col style="width: 124.333333px">
<col style="width: 124.333333px">
<col style="width: 124.333333px">
</colgroup>
<thead>
  <tr>
    <th class="tg-0pky" colspan="6">GRID B</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-rv8b"><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000">Mark</span></td>
    <td class="tg-cscf"><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Aims, Objectives and Intentions</span></td>
    <td class="tg-6e8n"><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Collection and analysis of Feedback</span></td>
    <td class="tg-6e8n"><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Positive reflections </span></td>
    <td class="tg-6e8n"><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Potential Improvements</span></td>
    <td class="tg-abx8"><span style="font-weight:700;font-style:normal;text-decoration:none;color:#000">Overall quality of written communication</span></td>
  </tr>
  <tr>
    <td class="tg-f7v4"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">5</span></td>
    <td class="tg-iks7"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Fully appropriate aims and objectives that are clear, attainable, and appropriate.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Fully developed discussion of intentions with reasons, and the specific actions to accomplish them.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Fully developed plan for collecting appropriate feedback from the audience.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Detailed analysis of the quantity and quality of feedback received using meaningful summary techniques.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Fully developed discussion of what went well, and why.</span><br><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Clear and detailed reflection on success of meeting the overall aims and objectives.</span><br><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Characterised by mature reflective judgement on the impact of the work.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Fully developed  discussion of what did not work well, and how things could be improved.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Clear reflection on failure of meeting the overall aims and objectives.</span><br><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Characterised by mature reflective judgement on the impact of the work.</span></td>
    <td class="tg-0lax"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Ideas expressed clearly, concisely, and with excellent structure. </span></td>
  </tr>
  <tr>
    <td class="tg-f7v4"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">4</span></td>
    <td class="tg-iks7"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Appropriate aims and objectives that are mostly clear, attainable, and appropriate.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Appropriate discussion of intentions.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Developed methods of feedback collection feedback from the audience.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Analysis of the quantity or quality of feedback received using meaningful summary techniques.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Developed discussion of what went well, and why.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Clear reflection on success of meeting the overall aims and objectives.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Developed discussion of what did not work well</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Clear reflection on failures of meeting the overall aims and objectives.</span></td>
    <td class="tg-0lax"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Ideas are generally expressed well, and with appropriate structure.</span></td>
  </tr>
  <tr>
    <td class="tg-llyw"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">3</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Fairly clear aims and objectives some of which are clear, attainable, and appropriate.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Partial discussion of intentions/reasons.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Some evidence of feedback collected, but of varying quality and usefulness.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Some discussion/analysis, possibly presented inefficiently.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Some awareness of what went well and only partial discussion of the reasons for this.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Some awareness of what did not work well and only partial discussion of the reasons for this.</span></td>
    <td class="tg-0lax"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Ideas are generally expressed fairly clearly, with reasonably appropriate structure.</span></td>
  </tr>
  <tr>
    <td class="tg-llyw"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">2</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Mostly unhelpful aims and objectives, which are not clear, obtainable or appropriate.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Minimal discussion of intentions/reasons.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Minimal planning for feedback leading to little discussion or analysis.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Minimal awareness of what went well </span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Obvious success points missed or not discussed.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Minimal awareness of what went did not work  well </span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Obvious failure points missed or not discussed</span></td>
    <td class="tg-0lax"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Ideas are rarely expressed coherently.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Structure is less appropriate.</span></td>
  </tr>
  <tr>
    <td class="tg-llyw"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">1</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Aims or objectives are unhelpful or vague, and few or none are clear or obtainable.</span><br><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Very limited discussion of intentions/reasons.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Very limited  planning for feedback collection and little or no discussion or analysis.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Very limited awareness/reflection on any success.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Very limited awareness/reflection on any failure.</span></td>
    <td class="tg-0lax"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">Ideas are expressed incoherently.  Limited structureD</span></td>
  </tr>
  <tr>
    <td class="tg-llyw"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000">0</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">No aims or objectives set</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">No attempt at feedback collection, discussion, or analysis.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">No awareness of positive  aspects of work.</span></td>
    <td class="tg-c6of"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">No awareness of negative  aspects of work..</span></td>
    <td class="tg-0lax"><span style="font-weight:400;font-style:normal;text-decoration:none;color:#000;background-color:transparent">No written work submitted.</span></td>
  </tr>
</tbody>
</table>

</details>

-->

<!--chapter:end:03-Assessment.Rmd-->

---
output:
  html_document: default
  pdf_document: default
---
# Masterclasses{-}
<!-- This is a spoiler in gitbook, html and epub formats, and normal text otherwise. -->

The Communicating Maths cohort will deliver 6 masterclasses over two weekends. Details will be listed below in due course.

<!--
Please find your group below to find details of your delivery group and the series you will attend.

<details>
<summary>Bath 18.3.23. </summary> 

::: {.information data-latex=""}
**Date:** *18.3.23*.

**Time:** *10:00-12:30*.

**Location:** *Bath University Campus*.

**Audience:** *Year 9, approx 100 participants*.

**University Mentor:** *Tam*.

**Masterclass Contact** *Chris Budd mascjb@bath.ac.uk*.

**Group Members:** *Joy Boh, Ashley Higgs, Chloe Howcroft, Lucia Lopez, Haranja Sivaneswaran, Jodie Young.*

**Initial pitch:** This group will pitch their initial ideas for their masterclass to the rest of the group at 12:20 on 9/3/23. You should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.

**Feedback:** After you have delivered your Masterclass you will receive verbal feedback, to support your written evaluation. This will be given by your mentor, who observed. Feedback slots will be approx 20 minutes long and during the 12:15-13:05 timetabled time on 30/3/23. You will be expected to ask your mentor reflective questions to support your evaluation.

:::
</details>

<details>
<summary>Oxford 18.3.23. </summary> 


::: {.information data-latex=""}
**Date:** *18.3.23*.

**Time:** *10:00-12:30*.

**Location:** *Oxford Brookes Campus*.

**Audience:** *Sixth form, approx 30 participants*.

**University Mentor:** *Ben*.

**Masterclass Contact** *Sam Kamparis s.kamperis@brookes.ac.uk*.

**Group Members:** *Tom Eves, Zoe Fairfax, Alankrit Mata, Anna Quinn, Rhea Shah.*

**Initial pitch:** This group will pitch their initial ideas for their masterclass to the rest of the group at 12:20 on 10/3/23. You should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.

**Feedback:** After you have delivered your Masterclass you will receive verbal feedback, to support your written evaluation. This will be given by your mentor, who observed. Feedback slots will be approx 20 minutes long and during the 12:15-13:05 timetabled time on 30/3/23. You will be expected to ask your mentor reflective questions to support your evaluation.

:::
</details>

<details>
<summary>Holyport College 18.3.23. </summary> 

::: {.information data-latex=""}
**Date:** *18.3.23*.

**Time:** *9:30-12:00*.

**Location:** *Holyport College*.

**Audience:** *Year 9, approx 45 participants*.

**University Mentor:** *Waleed*.

**Masterclass Contact** *Daniel Hubbard rimasterclasses@holyportcollege.org.uk*.

**Group Members:** *Andrew McGrath ,Kamilla Bugno,Ewan Partington, Samantha Perryman, Olivia Wiseman.*

**Initial pitch:** This group will pitch their initial ideas for their masterclass to the rest of the group at 12:40 on 9/3/23. You should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.

**Feedback:** After you have delivered your Masterclass you will receive verbal feedback, to support your written evaluation. This will be given by your mentor, who observed. Feedback slots will be approx 20 minutes long and during the 12:15-13:05 timetabled time on 30/3/23. You will be expected to ask your mentor reflective questions to support your evaluation.
:::
</details>

<details>
<summary>Bath 25.3.23. </summary> 


::: {.information data-latex=""}
**Date:** *25.3.23*.

**Time:** *10:00-12:30*.

**Location:** *Bath University Campus*.

**Audience:** *Year 9, approx 100 participants*.

**University Mentor:** *Ben*.

**Masterclass Contact** *Chris Budd mascjb@bath.ac.uk*.

**Group Members:** *Abigail Bennett, Tosia Ciszek, Mirren Derby,Timi Folaranmi, Molly Maguire-King, Tali Shear*

**Initial pitch:** This group will pitch their initial ideas for their masterclass to the rest of the group at 12:40 on 10/3/23. You should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.

**Feedback:** After you have delivered your Masterclass you will receive verbal feedback, to support your written evaluation. This will be given by your mentor, who observed. Feedback slots will be approx 20 minutes long and during the 12:15-13:05 timetabled time on 30/3/23. You will be expected to ask your mentor reflective questions to support your evaluation.
:::
</details>

<details>
<summary>Exeter 25.3.23. </summary> 

::: {.information data-latex=""}
**Date:** *25.3.23*.

**Time:** *9:30-12:00*.

**Location:** *Exeter School of Maths*.

**Audience:** *Year 9, approx 30 participants*.

**University Mentor:** *Tam*.

**Masterclass Contact** *Sophie Brown SophieBrown@exeterms.ac.uk*.

**Group Members:** *Sam Cheung, Lana Gregory, Ella Hidveghy, Rebecca Knight, Mira Balaji.*

**Initial pitch:** This group will pitch their initial ideas for their masterclass to the rest of the group at 13:20 on 10/3/23. You should prepare a 10 minute overview of your masterclass showing any relevant material. After this, you can expect to receive questions and feedback from your lecturers and peers for approx 10 minutes.

**Feedback:** After you have delivered your Masterclass you will receive verbal feedback, to support your written evaluation. This will be given by your mentor, who observed. Feedback slots will be approx 20 minutes long and during the 12:15-13:05 timetabled time on 30/3/23. You will be expected to ask your mentor reflective questions to support your evaluation.
:::
</details>



<!--chapter:end:04-Masterclasses.Rmd-->

---
output:
  html_document: default
  pdf_document: default
---
# School Placements{-}

A list of arranged placements will be listed below for those who opted for school placement for their second Mathematical Interaction in due course.
<!--

|     Time              |     First room                                                |     Second room                                                     |
|-----------------------|-------------------------------------------------------------|---------------------------------------------------------------------|
|     9:50-10:50    |                                       |     Year 9 mixed ability comp sci lesson in a computer room- ABI    |
|     11:10-12:10       |     Year 8 top set -ANNA                                    | Year 10 top set - MIRA & RHEA                                                                     |
|     12:10-13:10       |     Year 7 set 1 -ZOE                                       |     Year 7 set 2- CHLOE                                             |
|     13:10-13:50       |     Lunchtime enrichment $i^2$ club – ASHLEY and JOY    |                                                                     |
|     13:50-14:50       |     Year 9 top set EWAN                        |                                                                     |



<!--chapter:end:05-School_Placements.Rmd-->

